"""ISO 3166-1 alpha-2 nationalities published by the API.

This catalogue is base-code data and not a table. Countries change rarely, a
row nobody may edit adds a migration and a seed without adding a capability,
and keeping it here lets the registration schema validate a code without
touching the database. Names are in Spanish and the tuple is ordered by name
with diacritics folded, so the order does not depend on the server locale.

Regenerating: the names come from CLDR through the ICU data bundled with
Node, excluding the codes ISO 3166-1 does not assign officially, namely the
exceptionally reserved (AC, CP, CQ, DG, EA, IC, TA), the user-assigned
(XA, XB, XK), the groupings (EU, EZ, QO, UN) and the unknown region (ZZ).
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Country:
    code: str
    name: str


COUNTRIES: tuple[Country, ...] = (
    Country("AF", "Afganistán"),
    Country("AL", "Albania"),
    Country("DE", "Alemania"),
    Country("AD", "Andorra"),
    Country("AO", "Angola"),
    Country("AI", "Anguila"),
    Country("AQ", "Antártida"),
    Country("AG", "Antigua y Barbuda"),
    Country("SA", "Arabia Saudí"),
    Country("DZ", "Argelia"),
    Country("AR", "Argentina"),
    Country("AM", "Armenia"),
    Country("AW", "Aruba"),
    Country("AU", "Australia"),
    Country("AT", "Austria"),
    Country("AZ", "Azerbaiyán"),
    Country("BS", "Bahamas"),
    Country("BD", "Bangladés"),
    Country("BB", "Barbados"),
    Country("BH", "Baréin"),
    Country("BE", "Bélgica"),
    Country("BZ", "Belice"),
    Country("BJ", "Benín"),
    Country("BM", "Bermudas"),
    Country("BY", "Bielorrusia"),
    Country("BO", "Bolivia"),
    Country("BA", "Bosnia y Herzegovina"),
    Country("BW", "Botsuana"),
    Country("BR", "Brasil"),
    Country("BN", "Brunéi"),
    Country("BG", "Bulgaria"),
    Country("BF", "Burkina Faso"),
    Country("BI", "Burundi"),
    Country("BT", "Bután"),
    Country("CV", "Cabo Verde"),
    Country("KH", "Camboya"),
    Country("CM", "Camerún"),
    Country("CA", "Canadá"),
    Country("BQ", "Caribe neerlandés"),
    Country("QA", "Catar"),
    Country("TD", "Chad"),
    Country("CZ", "Chequia"),
    Country("CL", "Chile"),
    Country("CN", "China"),
    Country("CY", "Chipre"),
    Country("VA", "Ciudad del Vaticano"),
    Country("CO", "Colombia"),
    Country("KM", "Comoras"),
    Country("CG", "Congo"),
    Country("KP", "Corea del Norte"),
    Country("KR", "Corea del Sur"),
    Country("CR", "Costa Rica"),
    Country("CI", "Côte d’Ivoire"),
    Country("HR", "Croacia"),
    Country("CU", "Cuba"),
    Country("CW", "Curazao"),
    Country("DK", "Dinamarca"),
    Country("DM", "Dominica"),
    Country("EC", "Ecuador"),
    Country("EG", "Egipto"),
    Country("SV", "El Salvador"),
    Country("AE", "Emiratos Árabes Unidos"),
    Country("ER", "Eritrea"),
    Country("SK", "Eslovaquia"),
    Country("SI", "Eslovenia"),
    Country("ES", "España"),
    Country("US", "Estados Unidos"),
    Country("EE", "Estonia"),
    Country("SZ", "Esuatini"),
    Country("ET", "Etiopía"),
    Country("PH", "Filipinas"),
    Country("FI", "Finlandia"),
    Country("FJ", "Fiyi"),
    Country("FR", "Francia"),
    Country("GA", "Gabón"),
    Country("GM", "Gambia"),
    Country("GE", "Georgia"),
    Country("GH", "Ghana"),
    Country("GI", "Gibraltar"),
    Country("GD", "Granada"),
    Country("GR", "Grecia"),
    Country("GL", "Groenlandia"),
    Country("GP", "Guadalupe"),
    Country("GU", "Guam"),
    Country("GT", "Guatemala"),
    Country("GF", "Guayana Francesa"),
    Country("GG", "Guernesey"),
    Country("GN", "Guinea"),
    Country("GQ", "Guinea Ecuatorial"),
    Country("GW", "Guinea-Bisáu"),
    Country("GY", "Guyana"),
    Country("HT", "Haití"),
    Country("HN", "Honduras"),
    Country("HU", "Hungría"),
    Country("IN", "India"),
    Country("ID", "Indonesia"),
    Country("IQ", "Irak"),
    Country("IR", "Irán"),
    Country("IE", "Irlanda"),
    Country("BV", "Isla Bouvet"),
    Country("IM", "Isla de Man"),
    Country("CX", "Isla de Navidad"),
    Country("NF", "Isla Norfolk"),
    Country("IS", "Islandia"),
    Country("AX", "Islas Aland"),
    Country("KY", "Islas Caimán"),
    Country("CC", "Islas Cocos"),
    Country("CK", "Islas Cook"),
    Country("FO", "Islas Feroe"),
    Country("GS", "Islas Georgia del Sur y Sandwich del Sur"),
    Country("HM", "Islas Heard y McDonald"),
    Country("FK", "Islas Malvinas"),
    Country("MP", "Islas Marianas del Norte"),
    Country("MH", "Islas Marshall"),
    Country("UM", "Islas menores alejadas de EE. UU."),
    Country("PN", "Islas Pitcairn"),
    Country("SB", "Islas Salomón"),
    Country("TC", "Islas Turcas y Caicos"),
    Country("VG", "Islas Vírgenes Británicas"),
    Country("VI", "Islas Vírgenes de EE. UU."),
    Country("IL", "Israel"),
    Country("IT", "Italia"),
    Country("JM", "Jamaica"),
    Country("JP", "Japón"),
    Country("JE", "Jersey"),
    Country("JO", "Jordania"),
    Country("KZ", "Kazajistán"),
    Country("KE", "Kenia"),
    Country("KG", "Kirguistán"),
    Country("KI", "Kiribati"),
    Country("KW", "Kuwait"),
    Country("LA", "Laos"),
    Country("LS", "Lesoto"),
    Country("LV", "Letonia"),
    Country("LB", "Líbano"),
    Country("LR", "Liberia"),
    Country("LY", "Libia"),
    Country("LI", "Liechtenstein"),
    Country("LT", "Lituania"),
    Country("LU", "Luxemburgo"),
    Country("MK", "Macedonia del Norte"),
    Country("MG", "Madagascar"),
    Country("MY", "Malasia"),
    Country("MW", "Malaui"),
    Country("MV", "Maldivas"),
    Country("ML", "Mali"),
    Country("MT", "Malta"),
    Country("MA", "Marruecos"),
    Country("MQ", "Martinica"),
    Country("MU", "Mauricio"),
    Country("MR", "Mauritania"),
    Country("YT", "Mayotte"),
    Country("MX", "México"),
    Country("FM", "Micronesia"),
    Country("MD", "Moldavia"),
    Country("MC", "Mónaco"),
    Country("MN", "Mongolia"),
    Country("ME", "Montenegro"),
    Country("MS", "Montserrat"),
    Country("MZ", "Mozambique"),
    Country("MM", "Myanmar (Birmania)"),
    Country("NA", "Namibia"),
    Country("NR", "Nauru"),
    Country("NP", "Nepal"),
    Country("NI", "Nicaragua"),
    Country("NE", "Níger"),
    Country("NG", "Nigeria"),
    Country("NU", "Niue"),
    Country("NO", "Noruega"),
    Country("NC", "Nueva Caledonia"),
    Country("NZ", "Nueva Zelanda"),
    Country("OM", "Omán"),
    Country("NL", "Países Bajos"),
    Country("PK", "Pakistán"),
    Country("PW", "Palaos"),
    Country("PA", "Panamá"),
    Country("PG", "Papúa Nueva Guinea"),
    Country("PY", "Paraguay"),
    Country("PE", "Perú"),
    Country("PF", "Polinesia Francesa"),
    Country("PL", "Polonia"),
    Country("PT", "Portugal"),
    Country("PR", "Puerto Rico"),
    Country("HK", "RAE de Hong Kong (China)"),
    Country("MO", "RAE de Macao (China)"),
    Country("GB", "Reino Unido"),
    Country("CF", "República Centroafricana"),
    Country("CD", "República Democrática del Congo"),
    Country("DO", "República Dominicana"),
    Country("RE", "Reunión"),
    Country("RW", "Ruanda"),
    Country("RO", "Rumanía"),
    Country("RU", "Rusia"),
    Country("EH", "Sáhara Occidental"),
    Country("WS", "Samoa"),
    Country("AS", "Samoa Americana"),
    Country("BL", "San Bartolomé"),
    Country("KN", "San Cristóbal y Nieves"),
    Country("SM", "San Marino"),
    Country("MF", "San Martín"),
    Country("PM", "San Pedro y Miquelón"),
    Country("VC", "San Vicente y las Granadinas"),
    Country("SH", "Santa Elena"),
    Country("LC", "Santa Lucía"),
    Country("ST", "Santo Tomé y Príncipe"),
    Country("SN", "Senegal"),
    Country("RS", "Serbia"),
    Country("SC", "Seychelles"),
    Country("SL", "Sierra Leona"),
    Country("SG", "Singapur"),
    Country("SX", "Sint Maarten"),
    Country("SY", "Siria"),
    Country("SO", "Somalia"),
    Country("LK", "Sri Lanka"),
    Country("ZA", "Sudáfrica"),
    Country("SD", "Sudán"),
    Country("SS", "Sudán del Sur"),
    Country("SE", "Suecia"),
    Country("CH", "Suiza"),
    Country("SR", "Surinam"),
    Country("SJ", "Svalbard y Jan Mayen"),
    Country("TH", "Tailandia"),
    Country("TW", "Taiwán"),
    Country("TZ", "Tanzania"),
    Country("TJ", "Tayikistán"),
    Country("IO", "Territorio Británico del Océano Índico"),
    Country("TF", "Territorios Australes Franceses"),
    Country("PS", "Territorios Palestinos"),
    Country("TL", "Timor-Leste"),
    Country("TG", "Togo"),
    Country("TK", "Tokelau"),
    Country("TO", "Tonga"),
    Country("TT", "Trinidad y Tobago"),
    Country("TN", "Túnez"),
    Country("TM", "Turkmenistán"),
    Country("TR", "Turquía"),
    Country("TV", "Tuvalu"),
    Country("UA", "Ucrania"),
    Country("UG", "Uganda"),
    Country("UY", "Uruguay"),
    Country("UZ", "Uzbekistán"),
    Country("VU", "Vanuatu"),
    Country("VE", "Venezuela"),
    Country("VN", "Vietnam"),
    Country("WF", "Wallis y Futuna"),
    Country("YE", "Yemen"),
    Country("DJ", "Yibuti"),
    Country("ZM", "Zambia"),
    Country("ZW", "Zimbabue"),
)

COUNTRY_NAMES: dict[str, str] = {country.code: country.name for country in COUNTRIES}
COUNTRY_CODES: frozenset[str] = frozenset(COUNTRY_NAMES)


def normalize_country_code(value: str) -> str:
    """Return the comparison form of a nationality as the client may type it."""
    return value.strip().upper()


def is_known_country(code: str) -> bool:
    return normalize_country_code(code) in COUNTRY_CODES


def country_name(code: str) -> str | None:
    """Return the name of a country, or None when the code is not in the catalogue.

    A row written before this catalogue existed may hold anything, and a
    profile still has to render.
    """
    return COUNTRY_NAMES.get(normalize_country_code(code))
